name: "Topcoder AI PR Reviewer Action"
description: "Perform code reviews and comments on diffs using Wipro's Lab45 AI API for LLM inference."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  LAB45_API_KEY:
    description: "Lab45 API key for LLM inference."
    required: true
  LAB45_API_MODEL:
    description: "LLM model name to use."
    required: false
    default: "gpt-4o"
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "git-pull-request"
  color: "green"
